### ISSUE TITLE
column.rb:158:in `sort_by': comparison of NilClass with 469762048 failed (ArgumentError)

### ISSUE THREAD

**Issue by Kondamon** [jyruzicka/omniboard#14]
I have updated rubyfocus to the latest version and OF to the new database format. However, now I get this error (with the default configure files of omniboard)
/.rvm/gems/ruby-2.2.1/gems/omniboard-1.0.1/lib/omniboard/column.rb:158:in `sort_by': comparison of NilClass with 469762048 failed (ArgumentError)

However, with my old configurations files there is no error. But when I change a context of a project, it disappears from the Kanban board. The columns within the board are configured to filter all projects with a single context e.g. "1 Priority". E.g. after changing project A's context to "2 Priority", it is not shown anymore in the Kanban, should be in the 2nd column. Also changing back the context again to the old value doesn't make the project reappear again.

**Comment by jyruzicka** [comment]
Hi Kondamon! This should have (hopefully) been fixed with the latest release of rubyfocus (about two minutes ago). Does an update (via `gem update && gem clean`) fix this issue?

**Comment by Kondamon** [comment]
👍🏻

**Comment by Kondamon** [comment]
I have found out that there ist still something wrong with omniboard/rubyfocus.

After updating rubyfocus as you have recommended, all projects where shown as expected.
But still, when I change a context of a single project, it disappears from the Kanban board. Also changing back the context again to the old value doesn't make the project reappear again.

**Comment by jyruzicka** [comment]
This has been reported by others! I suspect something weird is happening with context-change updates in patches. Will investigate and hopefully work out a fix soon.

**Comment by tvanyo** [comment]
It has something to do with the sync between device databases. Had the same problem but as soon as my phone database was in sync with my Mac's database everything appeared where I expected it. So instead of OF treating the Mac DB as the Truth, it is waiting for all databases to be in agreement. Definitely not expected.

**Comment by Kondamon** [comment]
I can reproduce this! When the Mac's database is in sync with my phone's database, the project reappears in omniboard.

**Comment by jyruzicka** [comment]
Yup! I know what the issue is here - OmniFocus' new V2 database format (that came out in V2.6.1 of OmniFocus) is a bit more terse in how it records updates to projects and tasks: in V1, if you make a change to a project's due date, for example, you would record *every single field* in the update patch. In V2, you'd *only* record that changed due date.

This means that if the program is set up to read V1 patches and it reads a V2 patch, it goes "Oh yup, this project should have a blank name/note/status/competion date, just a due date!" and applies changes as required. This got sorted in the last update of Rubyfocus.

However! Due to the way projects and tasks get treated in Omnifocus (protip: they're basically the same thing), Rubyfocus will currently auto-convert any updated project into a task (again, because it doesn't see the "project" tag inside that task, which to its mind means "Oh, this must have been downgraded to a task"). If you sync everything up, the Omni Sync Server (which knows what it is doing) applies all the patches to your base document, which means that Rubyfocus has no need to apply patches and goes by the original declaration (which includes the fact that *yes*, this is a project).

I currently have half a solution coded up, but got distracted by making a tiny ruby XML generator in the test helper (which does making testing for this sort of thing a lot easier, admittedly). I hope to get it out later on today (NZ time), so hopefully stuff will all get fixed up soon.

(Until I find the *next* issue caused by the new database format...)

**Comment by jyruzicka** [comment]
OK, should be fixed (I hope). Try updating and cleaning gems, and let me know if this bug disappears!

**Comment by Kondamon** [comment]
Thank you for your great effort! For me, it works now as expected. However, I couldn't install the latest version via gem update but via `git clone && gem build`

**Comment by tvanyo** [comment]
I second that, thanks for the efforts! I've gotten it all installed and
will let you know if something else pops up.

Todd
