### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Berendbordje** [jyruzicka/omniboard#17]
While installing gem "install omniboard-1.1.1.gem" I get the following error:

Fetching: mini_portile2-2.1.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I have done this with the admin account.

What to do?

**Comment by jyruzicka** [comment]
Hi there! It sounds like you'll need to `sudo`. This allows you to do things as superuser, which is sometimes required. In this case, you'll need to install as superuser because gem files are being installed to `/Library/Ruby/Gems`.

You can `sudo` a command like this:

```
sudo install omniboard-1.1.1.gem
```

The system will ask you for your password, but apart from that, everything should work as normal.

Let me know if this helps!
