### ISSUE TITLE
Where is STDOUT files folder?

### ISSUE THREAD

**Issue by henryfish** [jyruzicka/omniboard#4]
I'm not familiar with terminal and I was wondering where the STDOUT folder is when I tried to output.

**Comment by jyruzicka** [comment]
STDOUT is the standard output - that is, the terminal itself. It's not too handy in this case (unless you like reading raw html), but it means you can redirect the output to another script or to a file using OS X's inbuilt redirection commands. For example, if you want to redirect all the output into a file:

    omniboard > foo.html

This would put the output in the file `foo.html` rather than showing it to you on the terminal. Note that this is functionally equivalent to calling omniboard with the `-o` flag:

    omniboard -o foo.html
